name: Run Data Pipeline
# Run the data pipeline twice a day, at 12:00 and 20:00 UTC

on:
  schedule:
    - cron: "0 12,20 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      working-directory: src
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: Install locales
      run: |
        sudo apt-get install -yq tzdata locales
        sudo locale-gen en_US.UTF-8
        sudo locale-gen es_ES.UTF-8
        locale -a

    - name: Update datasets
      working-directory: src
      run: |
        echo ::set-env name=TIMESTAMP::"$(date +'%Y-%m-%d %H')"
        python ./update.py --verify simple

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        title: Automatic data update
        body: Data updated by GitHub Bot (${{ env.TIMESTAMP }})
        commit-message: Data updated by GitHub Bot (${{ env.TIMESTAMP }})
        branch-name: data-update
        branch-suffix: timestamp
